language: node_js
node_js:
  - "node"
notifications:
  email:
    on_failure: change
install:
  - npm install
script:
  - yarn test
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
  bucket: "uwbce-public"
  skip_cleanup: true
  region: "us-west-2"
